# https://pre-commit.com/
#
# Before first use: `pre-commit install`
# To run: `pre-commit run --all-files`
# To update: `pre-commit autoupdate`
#  - &flake8_dependencies below needs updated manually
#
# Be careful about linting that rewrites code syntax we want to test.
ci:
    # See: https://pre-commit.ci/#configuration
    autofix_prs: false
    autoupdate_schedule: quarterly
    skip: [no-commit-to-branch]
fail_fast: true
default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      # - id: check-symlinks
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.13
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
  # I don't yet trust ruff to do what autoflake does
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: [--in-place]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
      # - id: black-jupyter
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: v0.0.272
  #   hooks:
  #     - id: ruff
  #       args: [--fix-only, --show-fixes]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: &flake8_dependencies
        # These versions need updated manually
        - flake8==6.0.0
        - flake8-comprehensions==3.12.0
        - flake8-bugbear==23.6.5
        - flake8-simplify==0.20.0
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: *flake8_dependencies
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
        additional_dependencies: [tomli]
        files: ^(innerscope|docs)/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
  # `pyroma` may help keep our package standards up to date if best practices change.
  # This is probably a "low value" check though and safe to remove if we want faster pre-commit.
  - repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
      - id: pyroma
        args: [-n, "10", .]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch  # no commit directly to main
