name: PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'eriknw/innerscope'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools twine
      - name: Build wheel and sdist
        run: python -m build --sdist --wheel
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist
          if-no-files-found: error
      - name: Check with twine
        run: python -m twine check --strict dist/*
      - name: Publish to PyPI
        if: contains(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
