name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy-3.8", "pypy-3.9", "pypy-3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toolz pytest coverage
          pip install -e . --no-deps
      - name: PyTest
        run: |
          if [[ ${{ matrix.python-version }} != '3.12' ]]; then
            coverage run --branch -m pytest --doctest-modules --method bytecode
          fi
          coverage run -a --branch -m pytest --doctest-modules --method trace
          pytest --doctest-modules --method trace
      - name: Coverage
        run: |
          coverage xml
          coverage report --show-missing
      - name: codecov
        uses: codecov/codecov-action@v4
