name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy-3.8", "pypy-3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toolz pytest coverage
          pip install -e . --no-deps
      - name: PyTest
        run: |
          coverage run --branch -m pytest --doctest-modules --method bytecode
          coverage run -a --branch -m pytest --doctest-modules --method trace
          pytest --doctest-modules --method trace
      - name: Coverage
        if: (! contains(matrix.python-version, 'pypy'))
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version}}
          COVERALLS_PARALLEL: true
        run: |
          pip install coveralls
          coverage report --show-missing
          coveralls --service=github

  finish:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
